# @package _global_
defaults:
  - /common/sharpa_inhand
  - _self_
algo:
  num_envs: ${training.num_envs}
  max_iterations: 3000
  save_interval: 50
  checkpoint: null
  use_amp: false
  batch_size: 2048
  replay_buffer_n: 1280
  updates_per_step: 14
  learning_starts: 1
  policy_frequency: 2
  critic_hidden_dim: 512
training:
  env_steps_per_sync: 2
