defaults:
  - _self_
  - task: sharpa_inhand/mujoco
algo:
  algo: ppo
  seed: 1
  algorithm:
    use_clipped_value_loss: true
    schedule: adaptive
    max_grad_norm: 1.0
hydra:
  searchpath:
    - pkg://sharpa_rl_unilab.conf
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
  job_logging:
    root:
      handlers: [console]
