# @package _global_
defaults:
  - /common/task
  - /common/protocol
  - _self_
algo:
  num_envs: ${hardware.num_envs}
  num_steps_per_env: 8
  algorithm:
    value_loss_coef: 4.0
    entropy_coef: 0.01
    learning_rate: 0.001
    desired_kl: 0.02
    num_learning_epochs: 5
    num_mini_batches: 4
    clip_param: 0.2
    gamma: 0.99
    lam: 0.95
