"""Synchronous PPO training with fresh rollouts and explicit timeout targets."""

import time
from contextlib import ExitStack
from typing import Any, cast

import torch
from rsl_rl.algorithms import PPO
from rsl_rl.storage import RolloutStorage
from tensordict import TensorDict

from sharpa_rl_unilab.algos.hora.models import pack_actor
from sharpa_rl_unilab.algos.hora.on_policy import TeacherPPO, TeacherRolloutStorage
from sharpa_rl_unilab.tasks.sharpa_inhand.protocol import ACTION_DIM
from sharpa_rl_unilab.tasks.sharpa_inhand.teacher_env import SharpaTeacherEnv

from .checkpoints import save_teacher
from .configuration import algorithm_options
from .logging import EpisodeStatistics, TrainingLogger, create_run, training_counters
from .policy import make_models, observe_new_samples, policy_td, tensor_obs
from .rollouts import collect, timeout_rewards


def update_ppo(cfg, actor, critic, learner, raw, last_obs, counters, device):
    n = int(cfg.algo.num_envs)
    batch = tensor_obs(raw, device)
    packed = pack_actor(batch)
    t = packed.shape[0]
    counters["received"] += t * n
    dones = (batch["terminated"].bool() | batch["truncated"].bool()).float()
    corrected_reward = timeout_rewards(batch, critic, float(cfg.algo.algorithm.gamma))
    td = TensorDict({"policy": packed[0], "critic": batch["critic"][0]}, batch_size=n)
    storage = (
        learner.storage
        if isinstance(learner, PPO) and learner.storage.num_transitions_per_env == t
        else TeacherRolloutStorage("rl", n, t, td, [ACTION_DIM], device)
    )
    if learner is None:
        options = algorithm_options(cfg, PPO, extra_options=("kl_mode",))
        # PPO obtains KL from the actor adapter, configured by make_models.
        options.pop("kl_mode", None)
        learner = TeacherPPO(
            cast(Any, actor),
            cast(Any, critic),
            storage,
            device=device,
            **options,
        )
    assert isinstance(learner, PPO)
    learner.storage = storage
    # Preserve the log-prob generated by the collecting policy.
    for step in range(t):
        tr = RolloutStorage.Transition()
        tr.observations = TensorDict(
            {"policy": packed[step], "critic": batch["critic"][step]}, batch_size=n
        )
        with torch.no_grad():
            tr.values = critic(tr.observations)
        tr.actions = batch["actions"][step]
        tr.actions_log_prob = batch["actions_log_prob"][step]
        tr.distribution_params = (
            batch["behavior_mean"][step],
            batch["behavior_std"][step],
        )
        tr.rewards, tr.dones = corrected_reward[step], dones[step]
        storage.add_transition(tr)
    with torch.no_grad():
        learner.compute_returns(policy_td(last_obs, device))
    # Values/returns use the collecting critic's frozen statistics.
    # The update may change normalization, but behavior density
    # and old values remain exactly those of collection.
    observe_new_samples(actor, critic, packed, batch["critic"])
    metrics = cast(PPO, learner).update()
    updates = int(cfg.algo.algorithm.num_learning_epochs) * int(cfg.algo.algorithm.num_mini_batches)
    counters["optimizer_updates"] += updates
    counters["actor_updates"] += updates
    counters["critic_updates"] += updates
    counters["training_samples"] += (t * n // int(cfg.algo.algorithm.num_mini_batches)) * updates
    return learner, metrics


def train_ppo(cfg, progress_key, target, started):
    device = cfg.training.device
    n = int(cfg.algo.num_envs)
    run = create_run(cfg)
    actor, critic, learner = make_models(cfg, device)
    counters = training_counters()
    with ExitStack() as resources:
        env = SharpaTeacherEnv(cfg, n)
        resources.callback(env.close)
        obs, _ = env.reset(seed=int(cfg.algo.seed))
        episodes = EpisodeStatistics(n)
        logger = TrainingLogger(run, cfg, target)
        resources.callback(logger.close)
        logger.start(status="Waiting for first rollout...")
        save_interval = int(cfg.algo.save_interval)
        while counters[progress_key] < target:
            horizon = int(cfg.algo.num_steps_per_env)
            if progress_key == "received":
                horizon = min(horizon, (target - counters["received"]) // n)
            collector_metrics = {}
            raw, obs = collect(env, obs, actor, horizon, device, metrics=collector_metrics)
            counters["collected"] += horizon * n
            episodes.update(raw["rewards"], raw["terminated"], raw["truncated"])
            learner, metrics = update_ppo(cfg, actor, critic, learner, raw, obs, counters, device)
            counters["policy_version"] += 1
            metrics.update(counters)
            metrics.update(collector_metrics)
            metrics.update(episodes.metrics())
            metrics.update(
                policy_lag=0,
                wall_seconds=time.monotonic() - started,
                reuse_ratio=counters["training_samples"] / counters["received"],
            )
            logger.log(metrics)
            iteration = counters["policy_version"]
            if save_interval > 0 and iteration % save_interval == 0:
                path = run / f"teacher_iteration_{iteration}.pt"
                save_teacher(
                    path, cfg, actor, critic, learner, counters, time.monotonic() - started
                )
                logger.log_save(str(path))
        final = run / "teacher_final.pt"
        save_teacher(final, cfg, actor, critic, learner, counters, time.monotonic() - started)
        logger.log_save(str(final))
        logger.finish()
        return final
