defaults:
  - _self_
  - task: sharpa_inhand/mujoco
algo:
  algo: flashsac
  seed: 1
  gamma: 0.97
  tau: 0.01
  num_atoms: 101
  use_amp: true
  exploration:
    noise_zeta_mu: 2.0
    noise_zeta_max: 16
  algo_params:
    normalize_reward: true
    normalized_g_max: 5.0
    critic_num_blocks: 2
    actor_bc_alpha: 0.0
    critic_min_v: -5.0
    critic_max_v: 5.0
    temp_initial_value: 0.01
    temp_target_sigma: 0.15
    temp_target_entropy: null
    learning_rate_init: 3.0e-4
    learning_rate_peak: 3.0e-4
    learning_rate_end: 1.5e-4
    learning_rate_warmup_steps: 0
    learning_rate_decay_steps: 500000
    n_step: 1
    amp_dtype: auto
hydra:
  searchpath:
    - pkg://sharpa_rl_unilab.conf
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
  job_logging:
    root:
      handlers: [console]
